const data = {
    products: [
      {
        name: 'Ankara Gown',
        slug: 'blue-ankara',
        category: 'Ankara Gown',
        image: '/images/shirt1.jpg',
        price: 17000,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular Gown',
      },
      {
        name: 'Gray Ray',
        slug: 'gray-ray',
        category: 'Ankara Gown',
        image: '/images/shirt2.jpg',
        price: 18000,
        brand: 'Adidas',
        rating: 4.2,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular Gown',
      },
      {
        name: 'Overall Gown',
        slug: 'overall-gown',
        category: 'Ankara Gown',
        image: '/images/shirt3.jpg',
        price: 19500,
        brand: 'Raymond',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: ' A popular Gown',
      },
      {
        name: 'Spotted brown',
        slug: 'spotted-brown',
        category: 'Pants',
        image: '/images/pants1.jpg',
        price: 15000,
        brand: 'Oliver',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: ' Smart looking pants',
      },
      {
        name: 'Plinted Top',
        slug: 'plinted-top',
        category: 'Pants',
        image: '/images/pants2.jpg',
        price: 19500,
        brand: 'Zara',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular Plinted Top',
      },
      {
        name: 'Classic Pants',
        slug: 'classic-pants',
        category: 'Pants',
        image: '/images/pants3.jpg',
        price: 17500,
        brand: 'Casely',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular pants',
      },
    ],
  };



  export default data;